[2021-12-17 15:33:35,142] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: my_dag.training_model_A manual__2021-12-17T14:33:24.198229+00:00 [queued]>
[2021-12-17 15:33:35,154] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: my_dag.training_model_A manual__2021-12-17T14:33:24.198229+00:00 [queued]>
[2021-12-17 15:33:35,155] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-12-17 15:33:35,156] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2021-12-17 15:33:35,156] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-12-17 15:33:35,177] {taskinstance.py:1262} INFO - Executing <Task(PythonOperator): training_model_A> on 2021-12-17 14:33:24.198229+00:00
[2021-12-17 15:33:35,178] {standard_task_runner.py:52} INFO - Started process 12818 to run task
[2021-12-17 15:33:35,185] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'my_dag', 'training_model_A', 'manual__2021-12-17T14:33:24.198229+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmp5nmi_oyn', '--error-file', '/tmp/tmpud7n30qw']
[2021-12-17 15:33:35,188] {standard_task_runner.py:77} INFO - Job 12: Subtask training_model_A
[2021-12-17 15:33:35,261] {logging_mixin.py:109} INFO - Running <TaskInstance: my_dag.training_model_A manual__2021-12-17T14:33:24.198229+00:00 [running]> on host sofienkhanfir-VirtualBox
[2021-12-17 15:33:35,303] {taskinstance.py:1427} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=my_dag
AIRFLOW_CTX_TASK_ID=training_model_A
AIRFLOW_CTX_EXECUTION_DATE=2021-12-17T14:33:24.198229+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-12-17T14:33:24.198229+00:00
[2021-12-17 15:33:35,303] {python.py:152} INFO - Done. Returned value was: 8
[2021-12-17 15:33:35,320] {taskinstance.py:1270} INFO - Marking task as SUCCESS. dag_id=my_dag, task_id=training_model_A, execution_date=20211217T143324, start_date=20211217T143335, end_date=20211217T143335
[2021-12-17 15:33:35,377] {local_task_job.py:154} INFO - Task exited with return code 0
[2021-12-17 15:33:35,396] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
